
'use client';
import { useState } from 'react';
import { downloadJSON } from '@/lib/exportLocal';
import { toSlug } from '@/lib/util';
const STAGES=['Basics','Docs','Context','Ethics','Review'];
const defaultForm={name:'',region:'',lat:'',lng:'',keywords:'',summary:'',tips:'',themes:'',yearsStart:'',yearsEnd:'',documents:[],iiifManifest:''};
export default function Contribute(){const[i,setI]=useState(0);const[form,setForm]=useState(defaultForm);const[docs,setDocs]=useState([{title:'',url:'',type:''}]);const addDoc=()=>setDocs(d=>[...d,{title:'',url:'',type:''}]);const next=()=>setI(Math.min(i+1,STAGES.length-1));const back=()=>setI(Math.max(0,i-1));
  const save=()=>{const entry={id:toSlug(form.name),name:form.name,region:form.region,coordinates:[parseFloat(form.lat),parseFloat(form.lng)],keywords:form.keywords.split(',').map(s=>s.trim()).filter(Boolean),summary:form.summary,tips:form.tips,themes:form.themes.split(',').map(s=>s.trim()).filter(Boolean),years:[parseInt(form.yearsStart||'0'),parseInt(form.yearsEnd||'0')],documents:docs.filter(d=>d.title&&d.url)};const subs=JSON.parse(localStorage.getItem('vv:submissions')||'[]');subs.push(entry);localStorage.setItem('vv:submissions',JSON.stringify(subs));downloadJSON((entry.id||'entry')+'.json',entry);};
  return(<div className='space-y-6'><div className='card'><h1 className='text-2xl font-semibold'>Contribute</h1><p className='text-white/70'>Submit a culture/tradition with documents and context. Saved locally and exported as JSON for curators.</p></div>
  <div className='card space-y-3'><div className='text-sm text-white/60'>Step {i+1}/{STAGES.length}: {STAGES[i]}</div>
  {i===0&&(<div className='grid md:grid-cols-2 gap-3'><input placeholder='Name' className='rounded-xl bg-white/10 px-3 py-2' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder='Region' className='rounded-xl bg-white/10 px-3 py-2' value={form.region} onChange={e=>setForm({...form,region:e.target.value})}/><input placeholder='Latitude' className='rounded-xl bg-white/10 px-3 py-2' value={form.lat} onChange={e=>setForm({...form,lat:e.target.value})}/><input placeholder='Longitude' className='rounded-xl bg-white/10 px-3 py-2' value={form.lng} onChange={e=>setForm({...form,lng:e.target.value})}/><input placeholder='Keywords (comma-separated)' className='rounded-xl bg-white/10 px-3 py-2 md:col-span-2' value={form.keywords} onChange={e=>setForm({...form,keywords:e.target.value})}/></div>)}
  {i===1&&(<div className='space-y-2'>{docs.map((d,idx)=>(<div key={idx} className='grid md:grid-cols-3 gap-2'><input placeholder='Title' className='rounded-xl bg-white/10 px-3 py-2' value={d.title} onChange={e=>{const a=[...docs];a[idx].title=e.target.value;setDocs(a);}}/><input placeholder='URL' className='rounded-xl bg-white/10 px-3 py-2' value={d.url} onChange={e=>{const a=[...docs];a[idx].url=e.target.value;setDocs(a);}}/><input placeholder='Type (PDF, Catalog, IIIF...)' className='rounded-xl bg-white/10 px-3 py-2' value={d.type} onChange={e=>{const a=[...docs];a[idx].type=e.target.value;setDocs(a);}}/></div>))}<button className='ghost' onClick={addDoc}>+ Add document</button><input placeholder='IIIF Manifest URL (optional)' className='rounded-xl bg-white/10 px-3 py-2 w-full' value={form.iiifManifest} onChange={e=>setForm({...form,iiifManifest:e.target.value})}/></div>)}
  {i===2&&(<div className='grid md:grid-cols-2 gap-2'><textarea placeholder='Summary' rows={4} className='rounded-xl bg-white/10 px-3 py-2' value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><textarea placeholder='Tips / key concepts' rows={4} className='rounded-xl bg-white/10 px-3 py-2' value={form.tips} onChange={e=>setForm({...form,tips:e.target.value})}/><input placeholder='Themes (comma-separated)' className='rounded-xl bg-white/10 px-3 py-2 md:col-span-2' value={form.themes} onChange={e=>setForm({...form,themes:e.target.value})}/><input placeholder='Year (start)' className='rounded-xl bg-white/10 px-3 py-2' value={form.yearsStart} onChange={e=>setForm({...form,yearsStart:e.target.value})}/><input placeholder='Year (end)' className='rounded-xl bg-white/10 px-3 py-2' value={form.yearsEnd} onChange={e=>setForm({...form,yearsEnd:e.target.value})}/></div>)}
  {i===3&&(<div className='space-y-2 text-sm text-white/80'><p><b>Ethical declaration:</b> I confirm that sources are cited, culturally sensitive content is shared with respect, and rights are honored.</p><label className='flex items-center gap-2'><input type='checkbox'/> I agree.</label></div>)}
  {i===4&&(<div className='space-y-2'><div className='text-white/80'>Review your submission, then export JSON for curators.</div><button className='primary' onClick={save}>Export submission (JSON)</button></div>)}
  <div className='flex gap-2'><button className='ghost' onClick={back} disabled={i===0}>Back</button><button className='primary' onClick={next} disabled={i===STAGES.length-1}>Next</button></div>
  </div></div>);}
